name: Run Maven Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      api:
        image: seanwin/spartaacademyapi:ci
        ports:
          - 8080:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API..."
          until curl -s http://localhost:8080/api/courses; do
            sleep 2
          done

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: test with Maven
        run: mvn clean verify --file pom.xml -X

      - name: List files in target directory
        run: ls -R target

      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-html-reports/

      - name: Upload surefire test reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/surefire-reports/